---
- name: Install neovim
  homebrew:
    name: neovim

- block:
  - name: Add node repository
    become: yes
    shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -

  - name: Install nodejs
    become: yes
    apt:
      name: nodejs
      autoclean: yes
      autoremove: yes
      update_cache: yes

- block:
    - name: Create nvim config dir
      file:
        path: ~/.config/nvim
        state: directory

    - name: Download install script for dein.vim
      get_url:
        url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
        dest: ~/.config/nvim/installer.sh
      register: download_result
      until: download_result is succeeded
      retries: 3
      delay: 5

    - name: Install dein.vim
      shell: sh ~/.config/nvim/installer.sh ~/.cache/dein
      args:
        creates: ~/.cache/dein/repos/github.com/Shougo/dein.vim
      changed_when: false

  tags: dein_install

- block:
    - name: Put "dein.toml" to nvim-config
      file:
        src: '{{ dotfiles_path }}/.config/nvim/dein.toml'
        dest: ~/.config/nvim/dein.toml
        state: link
        force: yes
      changed_when: false

    - name: Put "dein_lazy.toml" to nvim-config
      file:
        src: '{{ dotfiles_path }}/.config/nvim/dein_lazy.toml'
        dest: ~/.config/nvim/dein_lazy.toml
        state: link
        force: yes
      changed_when: false

    - name: Put "init.vim" to nvim-config
      file:
        src: '{{ dotfiles_path }}/.config/nvim/init.vim'
        dest: ~/.config/nvim/init.vim
        state: link
        force: yes
      changed_when: false

  tags: neovim_configfiles_put
