---
- name: Install tmux
  homebrew:
    name: tmux

- name: Install tmux powerline pip dependencies
  pip:
    name: "{{ item }}"
    executable: pip3
  loop:
    - powerline-status
    - powerline-mem-segment
    - psutil
