---
- block:
    - name: Install packages
      become: yes
      apt:
        name: '{{ apt_packages }}'
        autoclean: yes
        autoremove: yes
        update_cache: yes

    - name: Upgrade all packages to the latest version
      become: yes
      apt:
        upgrade: safe
      changed_when: false

  tags: apt_install